# GitHub action to deploy SuperHero NET 7 API to Azure.

name: Deploy SuperHero NET 7 API

on:
    workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "AzureNET7API20240408193444"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup .Net Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 7.0.x

            - name: Install dependencies
              run: dotnet restore ./AzureNET7API/AzureNET7API.csproj

            - name: Build
              run: dotnet build ./AzureNET7API/AzureNET7API.csproj --configuration Release --no-restore
            
            # Publish
            - name: Publish
              run: dotnet publish ./AzureNET7API/AzureNET7API.csproj --configuration Release --output ./publish

            # Deploy to Azure
            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with: 
                app-name: ${{env.AZURE_WEBAPP_NAME}}
                publish-profile: ${{secrets.API_PUBLISH_SECRET}}
                package: ./publish

            
